version: "3.8"
services:
  #PHP Service
  bgs_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: bgs_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    env_file:
      - ./.env
    command: bash -c "echo 'Preparing migrations' && sleep 10 && php artisan migrate && php artisan passport:install && php-fpm"
    networks:
      - app-network
    depends_on:
      - bgs_db

  #Nginx Service
  bgs_webserver:
    image: nginx:alpine
    container_name: bgs_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "85:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/dev/:/etc/nginx/conf.d/
    networks:
      - app-network
    depends_on:
      - bgs_app

  #PostgeSQL Service
  bgs_db:
    image: postgres:latest
    container_name: bgs_db
    restart: on-failure
    tty: true
    ports:
      - "5485:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
