name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: alex-ac/github-action-ssh-docker-compose@master
        name: Docker-Compose Remote Deployment
        with:
          ssh_host: ${{ secrets.MEDSOURCE_KE_SSH_HOST }}
          ssh_private_key: ${{ secrets.MEDSOURCE_KE_SSH_PRIVATE_KEY }}
          ssh_user: ${{ secrets.MEDSOURCE_KE_SSH_USER }}
          docker_compose_prefix: medsource.ke
          docker_compose_filename: docker-compose-prod.yml
